### PR TITLE
fix: ensure correct MSSQL parameter conversion in where conditions

### LINKED ISSUE #11285: Missing MSSQL input type
### Issue description

In MSSQL, when using the "find" method with where conditions on a "varchar" column, the query runner fails to specify the parameter type, causing performance issues.

[Refer](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlserver/SqlServerQueryRunner.ts#L204)

### Expected Behavior

Typeorm should handle the parameter input to node-mssql correctly

### Actual Behavior

According to the [node-mssql driver docs](https://tediousjs.github.io/node-mssql/#input-name-type-value), the input type defaults to a JS data type. However, for "varchar," it appears to conflict with "nvarchar," leading to the wrong data type being used in queries.

As a result, runtime data conversion occurs, significantly impacting query performance (our application crashed under high load due to this issue).

For now, we're using a workaround by executing raw queries and manually handling SQL parameters. This resolved the performance issue, but it should be handled by the ORM itself.

### Steps to reproduce

1. Define a varchar column
```
@Index()
@Column({ type: 'varchar', nullable: true })
 memberId: string | null
```

2. Query the entity with where condition on that column
```
this.somEntityRepo.find({ where: { memberId: "someValue" } })
```
On a large dataset, you can verify the resources used by this query.

---

Workaround which resolved the performance issue
```
 await this.connection.query(`SELECT * FROM "someEntity" WHERE "memberId" = ${'someValue'}`)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Node.js version     | 20.16.0  |
| Typescript version  | 5.5.4 |
| TypeORM version     | 0.3.20 |
| mssql     | 10.0.4 |

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [x] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

### PR DESCRIPTION
**Pull request by sudhirt4**
Fixes input parameter conversion in SelectQueryBuilder when using an MSSQL connection.

Closes #11285

### Description of change

Instead of passing raw input paramters as it is this change uses the available driver.parametrizeValue method to convert parameters into MSSQL format. 

This implementation was referred from existing usage in [UpdateQueryBuilder](https://github.com/typeorm/typeorm/blob/master/src/query-builder/UpdateQueryBuilder.ts#L553) and [InsertQueryBuilder](https://github.com/typeorm/typeorm/blob/master/src/query-builder/InsertQueryBuilder.ts#L887)

Please note that this issue currently only fixes where condition when used under `.find` method. On testing it was not working for `.createQueryBuilder(..).where()` usage. Could use some insights on a proper approach to implement this parameter transformation.

### Pull-Request Checklist
- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #11285`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change (N/A)
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by sgarner** [comment]
So this is tangentially related to https://github.com/typeorm/typeorm/pull/10161

For clarity, the problem is that MSSQL requires query parameters to be typed, and if no type is given then the underlying node-mssql driver defaults to NVARCHAR. If the column is actually a VARCHAR and is indexed, SQL Server won't use the index due to the type mismatch.

File: src/query-builder/SelectQueryBuilder.ts [hunk 1]
```diff
@@ -4278,6 +4280,12 @@ export class SelectQueryBuilder<Entity extends ObjectLiteral>
                                       column.transformer,
                                       parameterValue,
                                   ))
+                    } else {
```
Comment (sgarner) [inline src/query-builder/SelectQueryBuilder.ts:4283]: Are you sure this path should be in the else branch here?

I think the value needs to be 'parametrized' [sic] regardless of whether the column has a value transformer or not. The transformer should be applied first, and then parameterization.

**Review by sgarner — CHANGES_REQUESTED** [review]
@sudhirt4 I've run the tests, and some are failing - can you have a look at it?

**Comment by sudhirt4** [comment]
> @sudhirt4 I've run the tests, and some are failing - can you have a look at it?

Updated with the changes. 

Figured out that params of type FindOperator had to be [handled separately](https://github.com/typeorm/typeorm/pull/11298/files#diff-52bea788267888fdbb5f795f0dfb61504f16bd43e0afdfa28848abb4435121b5R4290). Instead of changing other functions to handle this I have adjusted it here following the approach used in transformer just above this. Let me know if this pattern is acceptable.

Have updated the tests to include these scenarios as well

File: src/query-builder/SelectQueryBuilder.ts (hunk 1 above)
Comment (sudhirt4) [reply src/query-builder/SelectQueryBuilder.ts]: Makes sense, updated with changes✅ 

I was worried if there would be some return type from transformer that parametrize function could not handle but seems like it's working just fine.

File: src/query-builder/SelectQueryBuilder.ts [hunk 2]
```diff
@@ -4280,6 +4282,24 @@ export class SelectQueryBuilder<Entity extends ObjectLiteral>
...
+                                to: (v) => driver.parametrizeValue(column, v),
+                                from: (v) => v,
+                            })
+                        } else {
+                            parameterValue = driver.parametrizeValue(
+                                column,
+                                parameterValue,
+                            )
+                        }
+                    }
```
Comment (sgarner) [inline src/query-builder/SelectQueryBuilder.ts:4301]: Although this works, the comparison against `parameterValue.type` is premature; `parameterValue` might be anything but the `type` property comparison only applies when it is a `FindOperator` instance. Suggest the raw check be moved to the inner condition.

Also adding a comment to explain what this block does:

```suggestion
                    // MSSQL requires parameters to carry extra type information
                    if (this.connection.driver.options.type === "mssql") {
                        const driver = this.connection.driver as SqlServerDriver
                        if (parameterValue instanceof FindOperator) {
                            if (parameterValue.type !== 'raw') {
                                parameterValue.transformValue({
                                    to: (v) => driver.parametrizeValue(column, v),
                                    from: (v) => v,
                                })
                            }
                        } else {
                            parameterValue = driver.parametrizeValue(
                                column,
                                parameterValue,
                            )
                        }
                    }
```

**Review by sgarner — APPROVED** [review]
Thank you @sudhirt4 for your effort on this!

File: src/query-builder/SelectQueryBuilder.ts (hunk 2 above)
Comment (sudhirt4) [reply src/query-builder/SelectQueryBuilder.ts]: Updated ✅ I amended by commit to include these changes

**Review by sgarner — APPROVED** [review]
LGTM :tada:
