### PR TITLE
Fix: #8914

### LINKED ISSUE #8914: CLI does not support async DataSource
## Issue Description
Starting from the 0.3.0 version, CLI requires to specify the file with DataSource instance instead of `ormconfig`. When I am trying to export async created DataSource it fails

### Expected Behavior
Command ran successfully

### Actual Behavior
Command failed with error: `Error: Given data source file must contain export of a DataSource instance`

### Steps to Reproduce
Have your DataSource defined in the file:

```typescript
const buildDataSource = async () => {
  // Provided config-like functionality just for example, it will fail anyway with just async function
  const dbConfig = await config.get('database');

  return new DataSource({
    type: 'mysql',
    host: dbConfig.host,
    port: 3306,
    username: dbConfig.username,
    password: dbConfig.password,
    database: dbConfig.database,
    logging: true,
    entities: typeormEntities,
    migrations: [ './src/components/database/migrations/**/*.ts' ]
  })
};

export default buildDataSource();
```

This works though:
```typescript
const buildDataSource = () => {
  return new DataSource({
    type: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    username: 'test',
    password: 'test',
    database: 'test',
    logging: true,
    entities: typeormEntities,
    migrations: [ './src/components/database/migrations/**/*.ts' ]
  })
};

export default buildDataSource();
```
### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Ubuntu 20.04.4 LTS     |
| Node.js version     | v16.13.0  | 
| Typescript version  | 4.6.3  | 
| TypeORM version     | 0.3.4  | 

### Relevant Database Driver(s)
I tested with `mysql` only but I do not think it is a driver problem at all

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by pavlovanton**
### Description of change
Support async import for DataSource in CLI. Fixes #8914 

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [ ] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/commands/CommandUtils.ts [hunk 1]
```diff
@@ -34,11 +34,10 @@ export class CommandUtils {
         }
 
         const dataSourceExports = []
-        for (let fileExport in dataSourceFileExports) {
-            if (
-                InstanceChecker.isDataSource(dataSourceFileExports[fileExport])
-            ) {
-                dataSourceExports.push(dataSourceFileExports[fileExport])
+        for (const fileExport of dataSourceFileExports) {
+            const awaitedFileExport = await fileExport
```
Comment (pleerock) [inline src/commands/CommandUtils.ts:38]: can't we add a check (something like `if (fileExport instanceof Promise)`) in order to make it more clear? also I recommend to add a comment line and explain why this change is needed.

Comment (pavlovanton) [reply src/commands/CommandUtils.ts:38]: @pleerock Sure, we can. It was decided to do so for sake of shortness (as far as `await` does not make (almost) any effect on non-`Promise` value this way).

But if it will be more clear this way, we can do like this (and the comment would be like that):
```typescript
// It is necessary to await here in case of the exported async value (Promise<DataSource>).
// e.g. the DataSource is instantiated with an async factory in the source file
const awaitedFileExport = fileExport instanceof Promise 
  ? await fileExport
  : fileExport;
```

What do you think?

Comment (Ginden) [reply src/commands/CommandUtils.ts:38]: @pleerock It's possible, but some people still use eg. Bluebird promises or compilation chains with `Promise` polyfills. There isn't any benefit in `instanceof Promise` checks, but only some obscure bug reports.

Comment (V1raNi) [reply src/commands/CommandUtils.ts:38]: I think `await`ing doesn't introduce any overhead, as MDN states - Returns the fulfilled value of the promise, or the value itself if it's not a Promise. And even if there is any, it is too small. So I would agree with @Ginden on this one

**Comment by ViniciussSantos** [comment]
I have some questions about how commandUtils.loadDataSource works and how to test this new bugfix. First, I'm trying to create a test that works for the current version first before adapting it to work with the async version:

```javascript
const dataSourceExports = []
for (let fileExport in dataSourceFileExports) {
    if (
        InstanceChecker.isDataSource(dataSourceFileExports[fileExport])
    ) {
        dataSourceExports.push(dataSourceFileExports[fileExport])
    }
}
  if (dataSourceExports.length === 0) {
            throw new Error(
                `Given data source file must contain export of a DataSource instance`,
            )
        }
```
But for some reason the InstanceChecker if statement is always false and the error is always thrown in my test and I can't seem to understand why.


Right now, my test  involves a simple file exporting a dataSource instance like this: 
```javascript 
const options: DataSourceOptions = {
    type: "postgres",
    host: "localhost",
    port: 5432,
    username: "test",
    password: "test",
    database: "test",
    synchronize: true,
    entities: [Post, Author, Category],
}
const dataSource = new DataSource(options)

module.exports = dataSource
```
and I'm testing it like this: 

```javascript 
const DataSourcePath = __dirname + "/datasourceInstance"
        const response = await CommandUtils.loadDataSource(
            DataSourcePath,
        )
        expect(response).instanceOf(DataSource)
```
when I console.log dataSourceFileExports, I get the confirmation that it's actually a datasource instance:
image
but the instanceChecker never returns a true value. What am I doing wrong @Ginden @pleerock ?

**Comment by pleerock** [comment]
@ViniciussSantos not sure, you might need to debug and check the data source symbol values?

**Comment by jordanmnunez** [comment]
any update on pushing this through? Looks like it is really close

**Comment by texiontech** [comment]
when will release this issue.

**Review by jonfarzrh — APPROVED** [review]

**Comment by jonfarzrh** [comment]
@pavlovanton Nice work on this man!  It seems that your checklist should be updated to say tests are passing.  I'd be more then happy to write tests around this if it would get it in faster.  TY for all your guys work on TypeORM!
