### PR TITLE
fix: enable returning additional columns with MSSQL

### LINKED ISSUE #7100: SQL Server error when requesting additional returning columns
## Issue Description
#5361 changed the way SQL Server uses `OUTPUT` in `INSERT`/`UPDATE` queries, causing an error if additional columns are requested using `InsertQueryBuilder.returning()`.

### Expected Behavior

```typescript
connection.createQueryBuilder(Post, 'post')
    .insert()
    .values({ title: "TITLE" })
    .returning(["text"])
    .execute();

connection.createQueryBuilder(Post, 'post')
    .update()
    .set({ title: "TITLE" })
    .returning(["text"])
    .execute();
```

Should both execute without error and return additional column "text".

### Actual Behavior

```sql
DECLARE @OutputTable TABLE ("id" int);

INSERT INTO "post"("title", "text") OUTPUT INSERTED."text", INSERTED."id" INTO @OutputTable VALUES (@0, @1);

SELECT * FROM @OutputTable
```

`QueryFailedError: Error: Column name or number of supplied values does not match table definition.`

```sql
UPDATE "post" SET "title" = @1 OUTPUT INSERTED."text" INTO @OutputTable WHERE "id" IN (@0)
```

`QueryFailedError: Error: Must declare the table variable "@OutputTable".`

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [x] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by imnotjames**
### Description of change

fixes #7100 
closes #7101

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/query-builder/InsertQueryBuilder.ts [hunk 1]
```diff
@@ -85,14 +85,30 @@ export class InsertQueryBuilder<Entity> extends QueryBuilder<Entity> {
             // if update entity mode is enabled we may need extra columns for the returning statement
             // console.time(".prepare returning statement");
             const returningResultsEntityUpdator = new ReturningResultsEntityUpdator(queryRunner, this.expressionMap);
+
+            const returningColumns: ColumnMetadata[] = [];
+
+            if (Array.isArray(this.expressionMap.returning) && this.expressionMap.mainAlias!.hasMetadata) {
+                returningColumns.push(
```
Comment (imnotjames) [inline src/query-builder/InsertQueryBuilder.ts:92]: Use the helper to find columns by path
