### PR TITLE
fix: release query runner when there is no migration to revert

### LINKED ISSUE #11231: Error trying to revert last migration when there is none on Oracle
### Issue description

Running typeorm migration:revert command make oracle driver throw NJS-104 error

### Expected Behavior

Having a nice message saying there is nothing to do and close gracefully. 

### Actual Behavior

Running `typeorm migration:revert` when there is no migration to revert (`migrations` table is empty) make the following output :
```
No migrations were found in the database. Nothing to revert!
Error during migration revert:
Error: NJS-104: connection pool cannot be closed because connections are busy
    at Object.throwErr (C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\oracledb@6.3.0\node_modules\oracledb\lib\errors.js:603:10)
    at Pool.close (C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\oracledb@6.3.0\node_modules\oracledb\lib\pool.js:295:14)
    at Pool.close [as terminate] (C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\oracledb@6.3.0\node_modules\oracledb\lib\util.js:134:10)
    at C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\typeorm@0.3.19_oracledb@6.3.0\node_modules\typeorm\driver\oracle\OracleDriver.js:854:18
    at new Promise (<anonymous>)
    at OracleDriver.closePool (C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\typeorm@0.3.19_oracledb@6.3.0\node_modules\typeorm\driver\oracle\OracleDriver.js:853:16)
    at OracleDriver.disconnect (C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\typeorm@0.3.19_oracledb@6.3.0\node_modules\typeorm\driver\oracle\OracleDriver.js:255:20)
    at DataSource.destroy (C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\typeorm@0.3.19_oracledb@6.3.0\node_modules\typeorm\data-source\DataSource.js:184:27)
    at Object.handler (C:\Users\aperez3\Documents\dev\coopco\node_modules\.pnpm\typeorm@0.3.19_oracledb@6.3.0\node_modules\typeorm\commands\MigrationRevertCommand.js:68:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'NJS-104'
```

### Steps to reproduce

Create empty typeorm project and connect it to an oracle database.

Run `typeorm migration:revert` command

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 11|
| Node.js version     | v20.12.2  |
| Typescript version  | 5.7.2  |
| TypeORM version     | 0.3.20  |
| oracledb    | 6.3.0  |
| Database version     | 19c   |

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [X] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

### PR DESCRIPTION
**Pull request by mjr128**
avoid error when there is nothing to revert because datasource is destroyed and query runner is not released

fix: Error trying to revert last migration when there is none on Oracle
Closes: #11231

### Description of change
Update `MigrationExectuor.undoLastMigration()` to release the query runner when there is no migration to run. The query runner is released the same way it is done when there is a migration to revert.

This fixes #11231 and avoid an error message on oracle database when reverting without migration to revert.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #11231`
- [x] There are new or updated unit tests validating the change
- [N/A] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed a resource cleanup issue when reverting the last migration with no migrations present, preventing potential connection leaks and improving stability, including on Oracle.
* **Tests**
  * Added automated tests to verify that reverting the last migration with an empty migration list completes without errors and releases resources properly.

### CODE REVIEW

**Review by gioboa — COMMENTED** [review]
Thanks @mjr128 for your help
I added this PR in our release board

**Review by jovanadjuric — APPROVED** [review]

**Review by gioboa — APPROVED** [review]

**Review by alumni — APPROVED** [review]

**Review by gioboa — APPROVED** [review]

File: test/github-issues/11231/issue-11231.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
+import { expect } from "chai"
```
Comment (gioboa) [inline test/github-issues/11231/issue-11231.ts:1]: We aren't creating tests for specific GitHub issues any more. Instead, tests should be added to the suites for the related functionality.

Can you please move these tests?

Thanks 🙏

Comment (gioboa) [reply test/github-issues/11231/issue-11231.ts:1]: is this PR still valid or is it abandoned?
