### PR TITLE
fix: fix up generated query with .update()

### LINKED ISSUE #11629: .update() generating a malformed query
### Issue description

When calling .update() passing an object.id, TypeORM is generating a malformed UPDATE query

### Expected Behavior

When having something like this in your code:

```typescript
const entity = await entityRepository.findOne({
  where: {
    id: 'string'
  }
})

await entityRepository.update(entity.id, {
  property: new Date()
})
``` 

TypeORM should generate a query like this:

``UPDATE "entity" SET "property" = $1, "updated_at" = CURRENT_TIMESTAMP WHERE "id" = $2``

### Actual Behavior

But it's generating a query like this:

``UPDATE "entity" SET "property" = $1, "updated_at" = CURRENT_TIMESTAMP WHERE "id" IN ($2)``

Causing a malformed query and affecting other rows

### Steps to reproduce

Create an entity using the following decorators as the primary key and with the specified PostgreSQL versions and TypeORM versions: 

```typescript
@PrimaryColumn('uuid', { generated: 'uuid', name: 'id' })
id: string
```

Call an update like this (same entity):

```typescript
const entity = await entityRepository.findOne({
  where: {
    id: 'string'
  }
})

await entityRepository.update(entity.id, {
  property: new Date()
})
``` 

See what query was generated.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  unix        |
| Node.js version     | 20.3.0 |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.20  |

### Additional Context

I am using ``@nestjs/typeorm@10.0.2`` to manage dependency injection and database connection. I've injected TypeORM's data source to perform these queries.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [x] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time, but I can support (using donations) development.

### PR DESCRIPTION
**Pull request by gioboa**
Close #11629

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] This pull request links relevant issues as `Fixes #00000`
- [ ] There are new or updated tests validating the change (`tests/**.test.ts`)
- [ ] Documentation has been updated to reflect this change (`docs/docs/**.md`)

### CODE REVIEW

File: src/query-builder/QueryBuilder.ts [hunk 1]
```diff
@@ -1243,12 +1274,12 @@ export abstract class QueryBuilder<Entity extends ObjectLiteral> {
                 !primaryColumn.relationMetadata &&
                 !primaryColumn.embeddedMetadata
             ) {
+                const values = normalized.map((id) =>
```
Comment (gioboa) [inline src/query-builder/QueryBuilder.ts:1277]: this is the real change.

File: src/query-builder/QueryBuilder.ts [hunk 2]
```diff
@@ -1243,12 +1274,12 @@ export abstract class QueryBuilder<Entity extends ObjectLiteral> {
...
+                    primaryColumn.getEntityValue(id, false),
+                )
                 return {
-                    [primaryColumn.propertyName]: In(
-                        normalized.map((id) =>
-                            primaryColumn.getEntityValue(id, false),
-                        ),
-                    ),
+                    [primaryColumn.propertyName]:
+                        values.length === 1 ? Equal(values[0]) : In(values),
```
Comment (alumni) [inline src/query-builder/QueryBuilder.ts:1282]: nit: There's another edge case when the length is 0, the generated SQL query is `column IN ()`, which is invalid as well.

Comment (gioboa) [reply src/query-builder/QueryBuilder.ts:1282]: is there an issue for that? I can create another PR to fix it.

File: test/functional/repository/update-by-criteria/repository-update-by-criteria.test.ts [hunk 3]
```diff
@@ -172,4 +173,44 @@ describe("repository > update methods", function () {
...
+                await postRepository.save(post1)
+                await postRepository.save(post2)
+
+                // verify the generated query uses = instead of IN
+                const qb = postRepository
+                    .createQueryBuilder()
+                    .update(UuidPost)
+                    .set({ title: "Updated Post #1" })
+                    .whereInIds(post1.id)
+
```
[the remark this answers is not in the document]
Comment (gioboa) [reply test/functional/repository/update-by-criteria/repository-update-by-criteria.test.ts:196]: fixed

File: src/query-builder/QueryBuilder.ts (hunk 2 above)
Comment (alumni) [reply src/query-builder/QueryBuilder.ts:1282]: I'm not sure there's an issue in github, I noticed it when using the `In` operator. Luckily for my driver it works when there's only one item in the array, but I always have to check if the array is empty before passing it to `In`.

Comment (gioboa) [reply src/query-builder/QueryBuilder.ts:1282]: let's create an issue with a test and I'll look at it

Comment (gioboa) [reply src/query-builder/QueryBuilder.ts:1282]: I don't want to add more complexity to fix a guessed (by my thoughts) problem.

**Review by naorpeled — APPROVED** [review]
