### PR TITLE
fix(upsert): handle update false or generatedType properly

### LINKED ISSUE #10889: Upsert with generated columns
### Issue description

Upsert does not respect the `update: false` option of generated columns

### Expected Behavior

I have this generated column;

```
  @Column({
    type: 'boolean',
    generatedType: 'STORED',
    update: false,
    insert: false,
    asExpression: `keepalive IS NOT NULL`,
    nullable: false,
  })
  inProgress: boolean;
```

I'm trying to upsert a record using the following code;

```
await Record.getRepository().upsert({ foo: 1, bar: 2 }}, ['foo', 'bar', 'inProgress']);
```

Even though `inProgress` is used as part of the ON CONFLICT clause, I wouldn't expect it to be updated. Yet, I get this error.

```
Error [QueryFailedError]: column "in_progress" can only be updated to DEFAULT
      at PostgresQueryRunner.query (/Users/christianblais/Code/github.com/unitoio/sync-services/services/scanner-worker/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:331:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at InsertQueryBuilder.execute (/Users/christianblais/Code/github.com/unitoio/sync-services/services/scanner-worker/node_modules/typeorm/query-builder/src/query-builder/InsertQueryBuilder.ts:163:33)
      [...]
      at async Test.run (node:internal/test_runner/test:632:9)
      at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
    query: 'INSERT INTO "public"."table"("foo", "bar" VALUES ($1, $2) ON CONFLICT ( "foo", "bar", "in_progress" ) DO UPDATE SET "foo" = EXCLUDED."foo", "bar" = EXCLUDED."bar", "in_progress" = EXCLUDED."in_progress", "keepalive" = EXCLUDED."keepalive"  RETURNING "foo", "bar", "keepalive", "in_progress"',
    parameters: [ '1', '2'],
    driverError: error: column "in_progress" can only be updated to DEFAULT
```

### Actual Behavior

I would have expected the DO UPDATE SET to not include generated columns, nor any other column with `update: false`.

### Steps to reproduce

I don't have reproducible steps at hand.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 20.11.1  |
| Typescript version  | 5.4  |
| TypeORM version     | 0.3.20  |

### Additional Context

No additional context.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by gioboa**
Close #10889

### Description of change

Prevent upsert from updating columns marked with `update: false` or `generatedType` by excluding them from the overwrite set.

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] This pull request links relevant issues as `Fixes #00000`
- [ ] There are new or updated tests validating the change (`tests/**.test.ts`)
- [ ] Documentation has been updated to reflect this change (`docs/docs/**.md`)

### CODE REVIEW

File: src/query-builder/InsertQueryBuilder.ts [hunk 1]
```diff
@@ -697,10 +699,20 @@ export class InsertQueryBuilder<
                     "on-duplicate-key-update",
                 )
             ) {
-                if (this.expressionMap.onUpdate) {
+                if (this.expressionMap.onIgnore) {
```
Comment (alumni) [inline src/query-builder/InsertQueryBuilder.ts]: unnecessary condition?

File: src/entity-manager/EntityManager.ts [hunk 2]
```diff
@@ -768,30 +768,34 @@ export class EntityManager {
...
-                    skipUpdateIfNoValuesChanged:
-                        options.skipUpdateIfNoValuesChanged,
-                    indexPredicate: options.indexPredicate,
-                    upsertType:
-                        options.upsertType ||
-                        this.connection.driver.supportedUpsertTypes[0],
-                },
-            )
+
+        qb.orUpdate(
```
Comment (alumni) [inline src/entity-manager/EntityManager.ts]: I think it was nicer before in the chain, you can read "insert().orUpdate()"

File: src/query-builder/InsertQueryBuilder.ts (hunk 1 above)
Comment (gioboa) [reply src/query-builder/InsertQueryBuilder.ts]: fixed

File: src/entity-manager/EntityManager.ts (hunk 2 above)
Comment (gioboa) [reply src/entity-manager/EntityManager.ts]: fixed

**Comment by guiligan** [comment]
🆙  any progress on this? this makes things a lot easier when fixed
