### PR TITLE
fix: resolve array modification bug in QueryRunner drop methods #11563

### LINKED ISSUE #11563: Array modification bug in QueryRunner drop methods causes elements to be skipped during iteration
### Issue description

Multiple QueryRunner implementations have a critical bug where iterating over arrays (foreign keys, indices, columns, unique constraints) and modifying them during iteration causes elements to be skipped due to in-place array modification.

### Expected Behavior

When methods like `dropForeignKeys()`, `dropIndices()`, `dropColumns()`, and `dropUniqueConstraints()` iterate over arrays using `for (const item of array)` and call individual drop methods, these individual methods internally remove items from the same array being iterated over. This causes the iterator to skip elements because the array indices shift during iteration, all items in the array should be dropped from the database table.

### Actual Behavior

Due to array modification during iteration, only some of the items are actually dropped. Elements get skipped because the array indices shift when items are removed during the loop.

For example, when dropping columns `[A, B, C]`:
1. Iterator starts at index 0, drops column A
2. Array becomes `[B, C]`, but iterator moves to index 1  
3. Iterator now points to column C (skipping B)
4. Only columns A and C are dropped, B remains

### Steps to reproduce

```typescript
import { DataSource } from 'typeorm';

// Create a table with multiple columns
const queryRunner = dataSource.createQueryRunner();
await queryRunner.createTable(new Table({
    name: 'test_table',
    columns: [
        { name: 'id', type: 'int', isPrimary: true },
        { name: 'col1', type: 'varchar', length: '255' },
        { name: 'col2', type: 'varchar', length: '255' },
        { name: 'col3', type: 'varchar', length: '255' },
        { name: 'col4', type: 'varchar', length: '255' }
    ]
}));

// Try to drop multiple columns at once
const table = await queryRunner.getTable('test_table');
const columnsToRemove = ['col1', 'col2', 'col3', 'col4'];

await queryRunner.dropColumns(table, columnsToRemove);

// Check remaining columns - some columns will still exist
const updatedTable = await queryRunner.getTable('test_table');
console.log(updatedTable.columns.map(c => c.name)); 
// Expected: ['id']
// Actual: ['id', 'col2', 'col4'] (col1 and col3 dropped, col2 and col4 remain)
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Any      |
| Node.js version     | Any      |
| Typescript version  | Any      |
| TypeORM version     | 0.3.x (all versions with affected QueryRunners) |

### Affected Methods and Files:
- `dropForeignKeys()` - SpannerQueryRunner, PostgresQueryRunner, CockroachQueryRunner
- `dropIndices()` - SpannerQueryRunner, PostgresQueryRunner, CockroachQueryRunner  
- `dropColumns()` - All major QueryRunners (Spanner, Postgres, MySQL, SQLServer, Oracle, CockroachDB, SAP, AuroraMySQL)
- `dropUniqueConstraints()` - PostgresQueryRunner, CockroachQueryRunner

### Example of problematic code pattern:
```typescript
async dropColumns(tableOrName: Table | string, columns: TableColumn[] | string[]): Promise<void> {
    // BUG: Iterating over array while modifying it
    for (const column of columns) {
        await this.dropColumn(tableOrName, column) // This modifies the 'columns' array internally
    }
}
```

### Proposed fix:
```typescript
async dropColumns(tableOrName: Table | string, columns: TableColumn[] | string[]): Promise<void> {
    // Create a copy of the array to avoid modification during iteration
    for (const column of [...columns]) {
        await this.dropColumn(tableOrName, column)
    }
}
```

### Safe methods (no changes needed):
- `dropCheckConstraints()` - Uses `Promise.all()` pattern
- `dropExclusionConstraints()` - Uses `Promise.all()` pattern
- SQLite-based QueryRunners - Use table cloning/recreation
- All `create*` methods - Don't modify arrays during iteration

This is a systematic issue affecting multiple database drivers with potential for data loss and inconsistent database states.

### Relevant Database Driver(s)

- [x] aurora-mysql
- [x] aurora-postgres
- [ ] better-sqlite3
- [x] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [x] mysql
- [ ] nativescript
- [x] oracle
- [x] postgres
- [ ] react-native
- [x] sap
- [x] spanner
- [x] sqlite
- [x] sqlite-abstract
- [ ] sqljs
- [x] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

### PR DESCRIPTION
**Pull request by taina0407**
### Description of change

This PR fixes a critical array modification bug in QueryRunner implementations where iterating over arrays while simultaneously modifying them during iteration causes elements to be skipped.

**Fixes:**
- #11563

**Problem:**
Multiple QueryRunner drop methods (`dropColumns`, `dropIndices`, `dropForeignKeys`, `dropUniqueConstraints`) had a classic "iteration while modifying" bug. When these methods iterate over arrays using `for (const item of array)` and call individual drop methods, the individual methods internally remove items from the same array being iterated over. This causes the iterator to skip elements because array indices shift during iteration.

**Example of the bug:**
When dropping columns `[A, B, C, D]`:
1. Iterator starts at index 0, drops column A
2. Array becomes `[B, C, D]`, but iterator moves to index 1  
3. Iterator now points to column C (skipping B)
4. Only columns A and C are dropped, B and D remain

**Solution:**
Changed all affected methods to iterate over a shallow copy of the input array using the spread operator `[...array]`. This ensures that modifications to the original array don't affect the iteration.

**Before (buggy):**
```typescript
for (const column of columns) {
    await this.dropColumn(tableOrName, column)
}
```

**After (fixed):**
```typescript
for (const column of [...columns]) {
    await this.dropColumn(tableOrName, column)
}
```

**Affected drivers and methods:**
- **dropColumns**: SpannerQueryRunner, PostgresQueryRunner, MysqlQueryRunner, SqlServerQueryRunner, OracleQueryRunner, CockroachQueryRunner, SapQueryRunner, AuroraMysqlQueryRunner
- **dropIndices**: SpannerQueryRunner, PostgresQueryRunner, MysqlQueryRunner, SqlServerQueryRunner, OracleQueryRunner, CockroachQueryRunner, SapQueryRunner, AuroraMysqlQueryRunner  
- **dropForeignKeys**: SpannerQueryRunner, PostgresQueryRunner, CockroachQueryRunner, SapQueryRunner
- **dropUniqueConstraints**: PostgresQueryRunner, SqlServerQueryRunner, OracleQueryRunner, CockroachQueryRunner

**Verification:**
- Added comprehensive regression test in #11563
- Added unit tests demonstrating the bug pattern and fix
- All tests pass and verify that all specified database objects are properly dropped
- Tested across multiple database drivers (Postgres, MySQL, SQL Server, Oracle, CockroachDB, Spanner, SAP, Aurora MySQL)

**Impact:**
This fix prevents potential data loss scenarios where users expect all specified database objects to be dropped but some are silently left behind due to the iteration bug.

### Pull-Request Checklist

-   [x] Code is up-to-date with the `master` branch
-   [x] This pull request links relevant issues as `Fixes #11563`
-   [x] There are new or updated unit tests validating the change
-   [ ] Documentation has been updated to reflect this change

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved reliability when dropping multiple columns, foreign keys, indices, or unique constraints at once by preventing skipped elements due to array modifications during iteration.

* **Tests**
  * Added new test cases to verify batch dropping of columns, foreign keys, indices, and unique constraints processes all items correctly without skipping any.

### CODE REVIEW

File: test/github-issues/11563/issue-11563.ts [hunk 1]
```diff
@@ -0,0 +1,493 @@
...
+} from "../../utils/test-utils"
+import { DataSource } from "../../../src/index"
+import { TableColumn } from "../../../src/schema-builder/table/TableColumn"
+import { TableIndex } from "../../../src/schema-builder/table/TableIndex"
+import { TableForeignKey } from "../../../src/schema-builder/table/TableForeignKey"
+import { TableUnique } from "../../../src/schema-builder/table/TableUnique"
+import { Table } from "../../../src/schema-builder/table/Table"
+import { TestEntity } from "./entity/TestEntity"
+
+describe("github issues > #11563 QueryRunner array modification during iteration bug", () => {
```
Comment (sgarner) [inline test/github-issues/11563/issue-11563.ts]: We are moving away from creating tests for specific GitHub issues.

Can you move these tests to the appropriate places in `test/functional/query-runner/drop-column.ts`, `test/functional/query-runner/drop-index.ts`, etc?

**Review by sgarner — CHANGES_REQUESTED** [review]
Great catch and fix, @taina0407 👌

File: test/github-issues/11563/issue-11563.ts (hunk 1 above)
Comment (taina0407) [reply test/github-issues/11563/issue-11563.ts]: Thanks for suggestion @sgarner, I've created 4 separate tests in `test/functional/query-runner`.

**Review by sgarner — APPROVED** [review]
Thanks for your contribution @taina0407 💜

**Comment by alumni** [comment]
Nice :)
