### PR TITLE
fix(types): add proper entity typing for `queryBuilder.update`

### LINKED ISSUE #10604: QueryBuilder not inferring entity type from `.update(YourEntity)`
### Issue description

The QueryBuilder returns a `UpdateQueryBuilder<any>` instead of correctly inferring the entity type

### Expected Behavior

Calling `.update(entity: Entity)` should return a correctly typed `UpdateQueryBuilder<Entity>`

```ts
const updateQueryBuilder = entityManager
    .createQueryBuilder()
    .update(Person);
   
// => expect updateQueryBuilder to be a UpdateQueryBuilder<Person>
```

### Actual Behavior

Calling `.update(Person)` returns a `UpdateQueryBuilder<any>`. 
However, `.update(Person, {})` returns a correctly typed `UpdateQueryBuilder<Person>`.

This suggests that a specific overload of the `update` function is not correctly typed:
```ts
/**
 * Creates UPDATE query and applies given update values.
 */
update(updateSet: QueryDeepPartialEntity<Entity>): UpdateQueryBuilder<Entity>;
/**
 * Creates UPDATE query for the given entity and applies given update values.
 */
update<Entity extends ObjectLiteral>(entity: EntityTarget<Entity>, updateSet?: QueryDeepPartialEntity<Entity>): UpdateQueryBuilder<Entity>;
```
The latter definition seems to work fine, however the first definition seems to be faulty. I think this is because an `Entity` is assingable to `QueryDeepPartialEntity<Entity>`, so using `.update(Person)` chooses the first definition. By using `.update(Person, {})` we explicitly use the second definition.

### Steps to reproduce

```ts
import { EntityManager } from 'typeorm';

class Person {}

const manager: EntityManager = 0 as any;
const builder = entityManager.createQueryBuilder().update(Person); // => UpdateQueryBuilder<any>
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |      Windows 11    |
| Node.js version     | 20.5.1 |
| Typescript version  | 5.1.3 |
| TypeORM version     | 0.3.19 |

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by OSA413**
Fixes #10604

### Description of change

~~This adds the proper type hint for update query builder when setting `update(Entity)`~~. Use case is described in the docs: https://github.com/typeorm/typeorm/blob/master/docs/update-query-builder.md

**BUT!** I noticed that current type overload for the single argument of `update` is expected to be `ObjectLiteral` (`QueryDeepPartialEntity<Entity>` actually), not an EntityClass/EntitySchema. Removing the problematic overload fixes the typing for `update`; ~~So, that's what I'm doing, I'm removing the problematic overload.~~

UPD: Managed to make it work with additional overload of the method.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by OSA413** [comment]
According to the failing tests, it actually expects EntityClass/EntitySchema or `ObjectLiteral` with the values to update.

**Comment by OSA413** [comment]
Here's playground link to the problem:
https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgEQIY1QZQgVygYwFM4BfOAMyghDgCIYBPMQ6EWgbgChP8IA7AM7wAgmDBoM2PETgBeOAAY4qAXD6EAboSjLVErLgKEuPADYrVAYVQ6EJbqPHoD0wgDpgfYDGCpTwAC9CAAoASjcYAAtCPmCAE2cpIzkAPkROOEy4AHpsuABVAWJ8FWIAYgBGDKyEyUMiNxBUPlQAc203fChCdEIARRxtBgAhHGBTOO0wtxwwWpDrKFCcvIBRAA9mfBhCOLgYCDgAI2J8ud6BodHxyagAHkWUgBo4fDxuvhhTBgLzncuoCMxhNtHdmgwUtVMrkCkVXqU4GUAExQuC1FxGNztGAAJUIkAE3mgDGCi3CXR6-0GgOuIKgwVoJSgtHCs3mYRWcA2Wx2ewOx1Of361KBN1BjxeAHkANKcEihIA

**Comment by OSA413** [comment]
Turns out the order of overloads makes difference, I'll update the code soon.

File: src/query-builder/QueryBuilder.ts [hunk 1]
```diff
@@ -209,6 +209,13 @@ export abstract class QueryBuilder<Entity extends ObjectLiteral> {
      */
     update(): UpdateQueryBuilder<Entity>
 
+    /**
+     * Creates UPDATE query for the given entity.
+     */
+    update<Entity extends ObjectLiteral>(
```
Comment (alumni) [inline src/query-builder/QueryBuilder.ts:215]: I'm surprised it's not already covered by the definition below:

https://github.com/typeorm/typeorm/pull/11296/files#diff-5725f0aa91cd5f33f502f605bcbc2ef2549c9f92a9ca1c984c03c2b8a80d73a5L227-L233
