### PR TITLE
fixes #4156 - QueryExpressionMap not cloning all values correctly

### LINKED ISSUE #4156: QueryExpressionMap doesn't clone all values correctly
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `postgres`

**TypeORM version:**

[x] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

`QueryExpressionMap`'s `clone` method doesn't clone all values correctly, specifically `insertColumns`, `whereEntities`, and `nativeParameters` are currently cloned by reference. The persistent reference to `nativeParameters` between clones causes issues with postgres as it generates the wrong parameter names (`$1`, `$2`, `$3`...) in `QueryBuilder.computeWhereParameter()`

```ts
...
const qb = connection.manager
  .createQueryBuilder("Post", "post");

await Promise.all([
  qb.clone().where({ id: 1 }).getOne(),
  qb.clone().where({ id: 1 }).getOne(),
]);

// postgres error - "could not determine data type of parameter $1"
```

I'm opening this issue so I can reference it in a PR that fixes this bug

### PR DESCRIPTION
**Pull request by pippinthegreat**
Fixes #4156

### CODE REVIEW

**Comment by birkir** [comment]
Thanks @pippinthegreat, paging mr @pleerock

File: src/query-builder/QueryExpressionMap.ts [hunk 1]
```diff
@@ -404,12 +404,12 @@ export class QueryExpressionMap {
         map.cacheDuration = this.cacheDuration;
         map.relationPropertyPath = this.relationPropertyPath;
         map.of = this.of;
-        map.insertColumns = this.insertColumns;
-        map.whereEntities = this.whereEntities;
+        map.insertColumns = this.insertColumns.map((column) => column);
+        map.whereEntities = this.whereEntities.map((entity) => ({ ...entity }));
```
Comment (pleerock) [inline src/query-builder/QueryExpressionMap.ts]: I don't think we should change those. I think your particular problem is in `nativeParameters`, isn't it?

Comment (pippinthegreat) [reply src/query-builder/QueryExpressionMap.ts]: okay, I've removed those changes
