### PR TITLE
fix: correctly keep query.data from ormOption for commit / rollback subscribers

### LINKED ISSUE #10150: queryRunner.data when provided by ormOptions is not provided to *TransactionCommit subscribers
### Issue description

Within a `transaction`, the `{ data }` object provided should also be provided to the `beforeTransactionCommit`, `afterTransactionCommit`, etc [subscribers](https://typeorm.io/listeners-and-subscribers#what-is-a-subscriber)

When calling method like `insert`, `update`, `save` and providing `OrmOptions`, for example:
```ts
const myEntity = new MyEntity({ id: 1, status 1 });

await manager.transaction(async (manager) => { 
  await queryRunner.insert(myEntity, { someData: true });
  await queryRunner.update({ ...myEntity, status: 2 });
}); 
```

### Expected Behaviour

This is what should be happening
```ts
    /**
     * Called after entity insert.
     */
    afterInsert(event: InsertEvent<any>) {
        console.log(`AFTER ENTITY INSERTED: `, event.queryRunner.data) // ✅ 
    }

    /**
     * Called after entity update.
     */
    afterUpdate(event: UpdateEvent<any>) {
        console.log(`AFTER ENTITY UPDATED: `, event.queryRunner.data) // ✅ 
    }

    /**
     * Called after transaction commit.
     */
    afterTransactionCommit(event: TransactionCommitEvent) {
        console.log(`AFTER TRANSACTION COMMITTED: `, event.queryRunner.data) // ✅  
    }
```

### Actual Behavior

This is what is happening
```ts
    /**
     * Called after entity insert.
     */
    afterInsert(event: InsertEvent<any>) {
        console.log(`AFTER ENTITY INSERTED: `, event.queryRunner.data) // ✅ 
    }

    /**
     * Called after entity update.
     */
    afterUpdate(event: UpdateEvent<any>) {
        console.log(`AFTER ENTITY UPDATED: `, event.queryRunner.data) // ✅ 
    }

    /**
     * Called after transaction commit.
     */
    afterTransactionCommit(event: TransactionCommitEvent) {
        console.log(`AFTER TRANSACTION COMMITTED: `, event.queryRunner.data) // ❌ 
    }
```

### Steps to reproduce

Here's a PR with the test that shows the issue (if you remove the fix it'll fail)
https://github.com/typeorm/typeorm/pull/10151/files

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Mac/Linux    |
| Node.js version     | 18.15.0  |
| Typescript version  | 5.0.4  |
| TypeORM version     | 0.3.1.0  |

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

### PR DESCRIPTION
**Pull request by nicolasroger17**
### Description of change

Keep `this.options.data` on the `queryRunner` for `subscribers` after the `transaction`

Fixes #10150 

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: test/functional/entity-subscriber/transaction-flow/entity-subscriber-transaction-flow.ts [hunk 1]
```diff
@@ -57,12 +64,14 @@ describe("entity subscriber > transaction flow", () => {
     after(() => closeTestingConnections(connections))
 
     it("transactionStart", async () => {
+        console.log({ connections })
```
Comment (arlo-borras) [inline test/functional/entity-subscriber/transaction-flow/entity-subscriber-transaction-flow.ts:67]: @nicolasroger17 This one should be removed, isn't it?

**Review by hinogi — APPROVED** [review]
LGTM
