### PR TITLE
fix #1373 - check require('mysql') call

### LINKED ISSUE #1373: mysql2 not `require`d properly in jest
Yet another issue with using typeorm x Jest!

It appears that Jest is creating a mock for `mysql` when I did not install `mysql` and want to use `mysql2` instead. Not only that but it waits until **after** the first attempt to require `mysql` to create the mock! This leads to a crazy heisenbug where the first time one calls `createConnection`, typeorm uses the `mysql2` driver, and the second time it uses the bogus `mysql` driver and crashes!

This issue can be worked around by adding an additional check to make sure we don't get garbage in return of the call to `require('mysql')`.

### PR DESCRIPTION
**Pull request by hmil**
#1373

### CODE REVIEW

File: src/driver/mysql/MysqlDriver.ts [hunk 1]
```diff
@@ -530,7 +530,9 @@ export class MysqlDriver implements Driver {
     protected loadDependencies(): void {
         try {
             this.mysql = PlatformTools.load("mysql");  // try to load first supported package
-
+            if (Object.keys(this.mysql).length === 0) {
+                throw new Error("'mysql' was found but it is empty. Falling back to 'mysql2'.");
```
Comment (hmil) [inline src/driver/mysql/MysqlDriver.ts]: The message is there for documentation purposes only. It is never shown to the user since the error gets caught right below.

Comment (pleerock) [reply src/driver/mysql/MysqlDriver.ts]: please add detailed comments on this code and explain why you did this and left github issue number.
