### PR TITLE
fix: avoid regex lookbehind for compatibility

### LINKED ISSUE #7026: QueryBuilder broken on web - Invalid regular expression: invalid group specifier name
## Issue Description
The QueryBuilder is broken in the new 0.2.29 release due to this change: https://github.com/typeorm/typeorm/pull/4760
Regex lookbehinds are not supported in on a lot of web environments, a fallback should be implemented.
This affects any driver that uses JavascriptCore (Safari, React Native, ...)

### Expected Behavior

I'd expect QueryBuilder to work

### Actual Behavior

QueryBuilder crashes with `Invalid regular expression: invalid group specifier name`

### Steps to Reproduce

I would add an reproducible example, however, I feel the issue is clear enough without?

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     React Native, Android     |
| Typescript version  | v4.0.5 | 
| TypeORM version     | v0.2.29 | 

### Additional Context

Relevant:
- https://bugs.webkit.org/show_bug.cgi?id=174931
- https://stackoverflow.com/questions/641407/javascript-negative-lookbehind-equivalent

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [x] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by mohd-akram**
### Description of change

Closes #7026

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/query-builder/QueryBuilder.ts [hunk 1]
```diff
@@ -624,12 +624,12 @@ export abstract class QueryBuilder<Entity> {
 
             if (replacementKeys.length) {
                 statement = statement.replace(new RegExp(
-                    `(?<=[ =\(]|^.{0})` +
+                    `([ =\(]|^.{0})` +
```
Comment (nebkat) [inline src/query-builder/QueryBuilder.ts:627]: Unrelated to this change but while we're here what is the effect of the `.{0}`?

**Comment by pleerock** [comment]
@Vluf @chriswep can you guys check if this fix works on react-native? If so, I'll merge this PR.

**Comment by Vluf** [comment]
@pleerock This PR fixes my issue on react-native, thanks!

File: src/query-builder/QueryBuilder.ts (hunk 1 above)
Comment (mohd-akram) [reply src/query-builder/QueryBuilder.ts:627]: Not sure, seems to have originated [here](https://github.com/typeorm/typeorm/commit/fe94b8fa5b7935e6c82161486e9958ff53f82790).

Comment (chriswep) [reply src/query-builder/QueryBuilder.ts:627]: considering the code-change: since this is not reverting the code to the last known working state but "just" removing the lookbehind expression from the regex - can you comment on how this code still accomplishes what it should do?
And maybe we should add a code-comment here about the regex-compatibility issue so that the next guy is not introducing the same thing again.

**Comment by chriswep** [comment]
> @Vluf @chriswep can you guys check if this fix works on react-native? If so, I'll merge this PR.

@pleerock to clarify, the issue is not with react-native per se, but with a lot of web-environments not supporting regex-lookbehind, including Safari. can't do a test right now, however since the lookbehind is removed it should not throw the error anymore. i can't speak into if the corresponding method still works correctly (see code commit above) - is this method tested properly?

**Comment by pleerock** [comment]
> @pleerock to clarify, the issue is not with react-native per se, but with a lot of web-environments not supporting regex-lookbehind, including Safari. 

yes, I got it. My point was to ask people (who use react native or web-env) to test these changes.

File: src/query-builder/QueryBuilder.ts (hunk 1 above)
Comment (mohd-akram) [reply src/query-builder/QueryBuilder.ts:628]: The [previous code](https://github.com/typeorm/typeorm/blob/2bf15ca913016ad07080c38c9fc3ee848b60ca4f/src/query-builder/QueryBuilder.ts#L574) did the same thing with the replacement. Lookahead/behind are just a simplification. I added a comment.

**Comment by pleerock** [comment]
Thank you @mohd-akram
