### PR TITLE
fix(query-builder): handle empty result set when offset exceeds total

### LINKED ISSUE #11640: getManyAndCount() returns incorrect count value for out-of-bounds skip
### Issue description

getManyAndCount() returns incorrect count value for out-of-bounds skip

### Expected Behavior

The following test case illustrates the regression introduced by #11524 :

```ts
// test/other-issues/lazy-count/lazy-count.ts

    it("should execute count query when skip is out-of-bounds", () =>
        Promise.all(
            connections.map(async function (connection) {
                await savePostEntities(connection, 5)

                const afterQuery = connection
                    .subscribers[0] as AfterQuerySubscriber
                afterQuery.clear()

                const [entities, count] = await connection.manager
                    .createQueryBuilder(Post, "post")
                    .take(10)
                    .skip(10) // Skip beyond the total number of records
                    .orderBy("post.id")
                    .getManyAndCount()

                expect(count).to.be.equal(5)
                expect(entities.length).to.be.equal(0)

                // The count query MUST be executed when skip is out-of-bounds
                expect(
                    afterQuery
                        .getCalledQueries()
                        .filter((query) => query.match(/(count|cnt)/i)),
                ).not.to.be.empty
            }),
        ))
```

### Actual Behavior

The count query should be executed when `skip` is out-of-bounds so that the correct `count` value is returned.

### Steps to reproduce

See unit test case

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    OSX Sequoia 15.5      |
| Node.js version     | 20.19.1  |
| TypeORM version     | 0.3.26  |

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

### PR DESCRIPTION
**Pull request by jeremyteyssedre**
Fixes #11640

### Description of change
This PR fixes a bug in lazy count optimization of geManyAndCount. (Introduced in #11524)

Currently, when using limit/offset, the count query can be skipped if the total can be deduced from the number of returned rows. However, there was an incorrect behavior when the offset value was greater than the total number of entities.

Before: lazyCount returned an incorrect total (equal to offset + 0).
Now: lazyCount correctly returns undefined in this case, forcing a proper COUNT(*) query to be executed.

### Pull-Request Checklist

-   [x] Code is up-to-date with the `master` branch
-   [x] This pull request links relevant issues as `Fixes #00000`
-   [x] There are new or updated unit tests validating the change
-   [ ] Documentation has been updated to reflect this change

## Summary by CodeRabbit

* **Bug Fixes**
  * Ensures total counts are correctly reported for paginated queries when offset/skip exceeds available items, avoiding missing or undefined totals for empty result sets.
* **Tests**
  * Added tests to confirm a separate count query runs in offset/skip scenarios, validating accurate totals even when no records are returned.

### CODE REVIEW

File: src/query-builder/SelectQueryBuilder.ts [hunk 1]
```diff
@@ -1939,6 +1939,10 @@ export class SelectQueryBuilder<Entity extends ObjectLiteral>
             return undefined
         }
 
+        if (entitiesAndRaw.entities.length === 0) {
+            return undefined;
+        }
```
Comment (sgarner) [inline src/query-builder/SelectQueryBuilder.ts]: In cases where skip/offset were not used, the lazy count can still be trusted when the result set is empty. So let's move this down and condition it on that:


```ts
        const hasSkip =
this.expressionMap.skip !== undefined &&
this.expressionMap.skip !== null &&
this.expressionMap.skip > 0
        const hasOffset =
this.expressionMap.offset !== undefined &&
this.expressionMap.offset !== null &&
this.expressionMap.offset > 0

        if (entitiesAndRaw.entities.length === 0 && (hasSkip || hasOffset)) {
            // when skip or offset were used and no results found, we need to execute a full count
            // (the given offset may have exceeded the actual number of rows)
            return undefined
        }
```

File: test/other-issues/lazy-count/lazy-count.ts [hunk 2]
```diff
@@ -266,6 +266,33 @@ describe("other issues > lazy count", () => {
             }),
         ))
 
+    it("run count query when offset is greater than total entities", () =>
```
Comment (sgarner) [inline test/other-issues/lazy-count/lazy-count.ts:297]: Could we have another test which verifies this works with `skip` and joined relations as well?

**Review by sgarner — CHANGES_REQUESTED** [review]
Good catch @jeremyteyssedre and thanks for the PR 💜

**Review by sgarner — APPROVED** [review]
LGTM!

Thanks for your contribution @jeremyteyssedre 💜

**Review by alumni — APPROVED** [review]
