### PR TITLE
fix: empty objects being hydrated when eager loading relations that have a `@VirtualColumn`

### LINKED ISSUE #10431: Eager loading relation that has a `@VirtualColumn` results in an empty Entity in the relation
### Issue description

See title

### Expected Behavior

I would expect that if the `@ManyToMany` relation results in no results in SQL, that the relation would be empty as well.

### Actual Behavior

But the relation is an array with 1 element in it that has all fields `null` but the `@VirtualColumn` field is set to `0` (its a virtual column to sum something).

### Steps to reproduce

I've added a test reproduction to `typeorm/typeorm` in PR #10432 

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | MacOS 13.3.1 |
| Node.js version     | 18.12  |
| Typescript version  | 4.9.5  |
| TypeORM version     | 0.3.14  |

### Additional Context

The behavior is the same as in #7450, but the `@VirtualColumn` adds a field that results in `0`, and so its not `null`. The fix for #7450 does not catch this.

If you remove the `@VirtualColumn` definition from `Category.ts`, the fix for #7450 work well again, but that just proves that #7450 has not fixed the root cause of this.

### Relevant Database Driver(s)

- [X] aurora-mysql
- [X] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [X] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

### PR DESCRIPTION
**Pull request by tolgap**
### Description of change

A reproduction and fixes #10431

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tolgap** [comment]
Not sure why the `test/github-issues` are not running. I cannot find any references to them in CircleCI.

But here's the error on my machine:
image

**Comment by tolgap** [comment]
@AlexMesser do you realize that `github-issues` tests are not running on any PR/commit?

**Comment by mohd-akram** [comment]
I ran into this as well and mentioned it before, but the CI has been broken since #10133. The `migration generate` test should be fixed or `describe.skip` re-added to it since that is where the premature termination happens.

File: src/query-builder/SelectQueryBuilder.ts [hunk 1]
```diff
@@ -2877,6 +2877,11 @@ export class SelectQueryBuilder<Entity extends ObjectLiteral>
                     })
                 })
             } else {
+                if (column.isVirtualProperty) {
```
Comment (alumni) [inline src/query-builder/SelectQueryBuilder.ts:2880]: @tolgap This just removes the VirtualColumn feature instead of fixing the issue that it has.

Probably this should've been solved in `RawSqlResultsToEntityTransformer`.

File: test/github-issues/10431/entity/Category.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+import { Product } from "./Product"
+
+@Entity()
+export class Category {
+    @PrimaryGeneratedColumn()
+    id: number
+
+    @VirtualColumn({
+        query: (alias) =>
+            `SELECT COUNT(*) FROM category WHERE id = ${alias}.id`,
```
Comment (alumni) [inline test/github-issues/10431/entity/Category.ts:17]: Missing double quotes around identifiers ;)

**Comment by scr4bble** [comment]
@AlexMesser If I understand correctly this PR brought a bug into the typeorm library which is described here: https://github.com/typeorm/typeorm/issues/10638
The issue is getting a lot of attention from community and it needs to be fixed. Do we know who is now responsible for reviewing and merging pull requests in this project?
I see you have merged this PR so I have tagged you with the question. Please spend few minutes on it so we can find a solution and move the things forward.

**Comment by alumni** [comment]
@scr4bble does https://github.com/typeorm/typeorm/pull/10927 fix your issue?

**Comment by scr4bble** [comment]
@alumni I have not verified any of the PRs as I currently don't have capacity to do it but my colleagues have invested some time into this and found the root cause and related issues/PRs. I am just trying to bring some attention to it so it gets fixed.

By quickly looking into the PR you posted - it looks to be removing the problematic code. It probably just needs attention from maintainers with deeper understanding of the library to verify the changes.
