### PR TITLE
fix: allow `FindOptionsWhere` to accept `LessThan` with Union

### LINKED ISSUE #9152: Can't use `LessThan` for Union field
## Issue Description

if a field is defined as Union like `1 | 2 | 3` or `'foo' | 'bar'`, operators `LessThan`, `MoreThan`, etc. raises a type error.

code example:

```ts
import { Entity, Column, getConnection, LessThan } from "typeorm";

type ValueType = 1 | 2 | 3;

@Entity()
export class User {
  @Column()
  foo: ValueType;
}

const repository = getConnection().getRepository(User);

const value = 3 as ValueType;

repository.findBy({
  foo: LessThan(value)
});
```

### Expected Behavior

works as if the field is defined as `number`

### Actual Behavior

```
Type 'FindOperator<1 | 2 | 3>' is not assignable to type '1 | 2 | 3 | FindOperator<1> | FindOperator<2> | FindOperator<3> | undefined'.
  Type 'FindOperator<1 | 2 | 3>' is not assignable to type 'FindOperator<1>'.
    Type '1 | 2 | 3' is not assignable to type '1'.
      Type '2' is not assignable to type '1'.ts(2322)
```

### Steps to Reproduce

[CodeSandbox](https://codesandbox.io/s/lingering-hill-36rb2u?file=/src/index.ts)

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     |   | 
| Typescript version  | 4.4.4  | 
| TypeORM version     | 0.3.6  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by tsugitta**
### Description of change

Fixes #9152 

Some CI have failed (edited: now CI passed by re-run), but it seems there is no problem based on the following points:

- I made changes to the type definitions but not to the implementation
- `tsc` succeeds
- The added tests do not depend on the database, and there is a successful CI for Postgres, etc.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
  - updates doesn't seem necessary
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/find-options/FindOptionsWhere.ts [hunk 1]
```diff
@@ -5,34 +5,37 @@ import { EqualOperator } from "./EqualOperator"
...
+    Original = Property,
+> = Property extends Promise<infer I>
     ? FindOptionsWhereProperty<NonNullable<I>>
     : Property extends Array<infer I>
     ? FindOptionsWhereProperty<NonNullable<I>>
     : Property extends Function
     ? never
     : Property extends Buffer
-    ? Property | FindOperator<Property>
+    ? Property | FindOperator<Property> | FindOperator<Original>
```
Comment (tsugitta) [inline src/find-options/FindOptionsWhere.ts:18]: The problem is that the union is narrowed down when `extends` is used. So we keep the original Union as the `Original` and pass the generics to the `FindOperator` while keeping the Union.

File: test/github-issues/9152/issue-9152.ts [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    before(
+        async () =>
+            (connections = await createTestingConnections({
+                entities: [Test],
+            })),
+    )
+    beforeEach(() => reloadTestingDatabases(connections))
+    after(() => closeTestingConnections(connections))
+
+    it("should not raise TypeScript error when LessThan with Union is passed to FindOptionsWhere", () =>
```
Comment (tsugitta) [inline test/github-issues/9152/issue-9152.ts:23]: In reality, it's enough to only see that the typecheck succeeds, and there is no need to add tests to be executed.

File: src/find-options/FindOptionsWhere.ts (hunk 1 above)
Comment (pleerock) [reply src/find-options/FindOptionsWhere.ts:18]: I wanted to make Distributive Conditional Types fix by adding square brakets instead of these changes, but I failed to make it to work.

Okay, one question I have - why do we need `FindOperator<Property> | FindOperator<Original>` and not just `FindOperator<Original>` now?
