### PR TITLE
fix: typescript 4.8 type issues #9331

### LINKED ISSUE #9331: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'. update(): UpdateQueryBuilder<Entity>;
### Expected Behavior
Just Build without any error.

## Issue Description
 Build Time error.
 It Work perfectly in development. When run build (tsc -p .)  then getting this error below.

```
node_modules/typeorm/query-builder/QueryBuilder.d.ts:84:34 - error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.

84     update(): UpdateQueryBuilder<Entity>;
                                    ~~~~~~

  node_modules/typeorm/query-builder/QueryBuilder.d.ts:24:44
    24 export declare abstract class QueryBuilder<Entity> {
                                                  ~~~~~~
    This type parameter might need an `extends ObjectLiteral` constraint.

node_modules/typeorm/query-builder/QueryBuilder.d.ts:88:75 - error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.

88     update(updateSet: QueryDeepPartialEntity<Entity>): UpdateQueryBuilder<Entity>;
                                                                             ~~~~~~

  node_modules/typeorm/query-builder/QueryBuilder.d.ts:24:44
    24 export declare abstract class QueryBuilder<Entity> {
                                                  ~~~~~~
    This type parameter might need an `extends ObjectLiteral` constraint.

node_modules/typeorm/query-builder/QueryBuilder.d.ts:92:114 - error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.

92     update<Entity>(entity: EntityTarget<Entity>, updateSet?: QueryDeepPartialEntity<Entity>): UpdateQueryBuilder<Entity>;      
                                                                                                                    ~~~~~~        

  node_modules/typeorm/query-builder/QueryBuilder.d.ts:92:12
    92     update<Entity>(entity: EntityTarget<Entity>, updateSet?: QueryDeepPartialEntity<Entity>): UpdateQueryBuilder<Entity>;  
                  ~~~~~~
    This type parameter might need an `extends ObjectLiteral` constraint.

node_modules/typeorm/query-builder/QueryBuilder.d.ts:96:95 - error TS2344: Type 'Entity' does not satisfy the constraint 'ObjectLiteral'.

96     update(tableName: string, updateSet?: QueryDeepPartialEntity<Entity>): UpdateQueryBuilder<Entity>;
                                                                                                 ~~~~~~

  node_modules/typeorm/query-builder/QueryBuilder.d.ts:24:44
    24 export declare abstract class QueryBuilder<Entity> {
                                                  ~~~~~~
    This type parameter might need an `extends ObjectLiteral` constraint.


Found 4 errors in the same file, starting at: node_modules/typeorm/query-builder/QueryBuilder.d.ts:84
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v16.15.0  | 
| Typescript version  | 4.8.2  | 
| TypeORM version     | 0.3.8  | 
| Express     | 4.18.1  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | yes|
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by regevbr**
### Description of change

Fixes #9331 - added type constraints on `Entity` to extend `ObjectLiteral`. See issue for more information

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/entity-manager/EntityManager.ts [hunk 1]
```diff
@@ -1354,8 +1354,8 @@ export class EntityManager {
      * sets current EntityManager instance to it. Used to work with custom repositories
      * in transactions.
      */
-    withRepository<Entity extends ObjectLiteral, R extends Repository<Entity>>(
-        repository: R,
+    withRepository<Entity extends ObjectLiteral, R extends Repository<any>>(
```
Comment (regevbr) [inline src/entity-manager/EntityManager.ts:1357]: This gives the right type inference with the new ObjectLiteral constraint

Comment (Ginden) [reply src/entity-manager/EntityManager.ts:1357]: `any`? Shouldn't it be `ObjectLiteral` too?

Comment (regevbr) [reply src/entity-manager/EntityManager.ts:1357]: it is constrained in the argument itself (line 1358), otherwise the type inference doesn't work

File: src/query-builder/QueryPartialEntity.ts [hunk 2]
```diff
@@ -8,12 +10,16 @@ export type QueryPartialEntity<T> = {
 /**
  * Make all properties in T optional. Deep version.
  */
-export type QueryDeepPartialEntity<T> = {
+export type QueryDeepPartialEntity<T> = _QueryDeepPartialEntity<
```
[the remark this answers is not in the document]
Comment (pleerock) [reply src/query-builder/QueryPartialEntity.ts:13]: solution is ugly, but looks like other solution requires to much re-do.

**Comment by pleerock** [comment]
Thank you for contribution! 🎉
