### PR TITLE
fix: resolve issue building eager relation alias for nested relations

### LINKED ISSUE #9944: Alias Issue With Nested Entity And Relations
### Issue description

Querying a nested entity which in turn has deeply nested relationships (eager) results in error (since 0.3.13)

### Expected Behavior

Consider the following example entities

- A has a **nested entity** B
- B has a *OneToMany* Relationship To C (eager)
- C has a *OneToMany* Relationship To D (eager)

Querying A should resolve all relations just fine without any error.

### Actual Behavior

Querying A results in the following error: `TypeORMError: "A__b" alias was not found. Maybe you forgot to join it?`

### Steps to reproduce

1. Clone the [reproduction repo](https://github.com/giz-berlin/typeorm-nested-entity-relation-repo)
2. Follow the steps in the README there and see the error code.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    macOS 13.3    |
| Node.js version     | 19.8.1  |
| Typescript version  | 4.5.2  |
| TypeORM version     | ^0.3.13  |

### Additional Context

This issue does **not** occur with `typeorm < 0.3.13`, so the issue has been introduced since 0.3.12.
It also does not happen when only having one level of relations (i.e. without entity `D` it works).

First investigations did show, that a11809e could be the culprit (especially <https://github.com/typeorm/typeorm/blame/master/src/find-options/FindOptionsUtils.ts#LL390-L395>) which was merged in #9680.

I only tested this with postgres.

If desired, I could provide the reproduction as a test but I am not sure how to fix this.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [X] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

### PR DESCRIPTION
**Pull request by JoseCToscano**
Fix alias error for nested relations. When loading eager relations from nested
levels only the first level was handled through the alias builder

Closes: #9944

### Description of change
When loading eager relations from nested levels only the first level was handled through the alias builder
resulting in the following error `TypeORMError: "A__b" alias was not found. Maybe you forgot to join it?`.
By appropiately handling deeply nested relations, just as any other relations they are able to be fetched as usual

Fixes #9944

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/naming-strategy/NamingStrategyInterface.ts [hunk 1]
```diff
@@ -162,11 +162,6 @@ export interface NamingStrategyInterface {
      */
     prefixTableName(prefix: string, tableName: string): string
 
-    /**
-     * Gets the name of the alias used for relation joins.
-     */
-    eagerJoinRelationAlias(alias: string, propertyPath: string): string
```
Comment (JoseCToscano) [inline src/naming-strategy/NamingStrategyInterface.ts:168]: This function was not being used at all, and just brings noise when trying to extend the interface

File: test/github-issues/9944/issue-9944.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+            dataSources.map(async (dataSource) => {
+                const aEntity = new A()
+                aEntity.b = new B()
+                aEntity.b.cs = [new C()]
+                await dataSource.manager.save(aEntity)
+
+                const [fetchedA] = await dataSource.manager.find(A)
+                expect(fetchedA.b).exist // Validates correct relation A.b is loaded
+                expect(fetchedA.b.cs).exist // Validates correct relation A.b.cs is loaded
+                expect(fetchedA.b.cs[0]).exist
```
Comment (JoseCToscano) [inline test/github-issues/9944/issue-9944.ts:39]: Before the fix, running this test resulted in the `TypeORMError: "A__b" alias was not found. Maybe you forgot to join it?`

With the fix it runs perfectly. I jut added these three assertions to make sure that data from nested relations was indeed loaded correctly

File: src/driver/DriverUtils.ts [hunk 3]
```diff
@@ -127,14 +127,16 @@ export class DriverUtils {
...
-                      buildOptions && buildOptions.joiner
-                          ? buildOptions.joiner
-                          : "_",
-                  )
+        const joiner =
+            buildOptions && buildOptions.joiner ? buildOptions.joiner : "_"
+
+        let newAlias = alias.length === 1 ? alias[0] : alias.join(joiner)
+
+        const hasNestedRelations = newAlias.includes(".")
```
Comment (felix-gohla) [inline src/driver/DriverUtils.ts:135]: Is there some kind of constant that defines this as the relations joiner in typeorm? I've skimmed through the repo and didn't find one. Maybe you have more insight. 😊

File: src/driver/DriverUtils.ts [hunk 4]
```diff
@@ -127,14 +127,16 @@ export class DriverUtils {
...
+        if (hasNestedRelations) {
+            newAlias = newAlias.replace(/\./g, joiner)
```
Comment (felix-gohla) [inline src/driver/DriverUtils.ts:137]: Are there some edge cases like dots in table names that would be affected by this? At least in postgres, I am able to create tables with dots and then use double quote marks to show that this is a name.

**Review by felix-gohla — COMMENTED** [review]
Apart from the nits: Works! Thank you for fixing that issue.

File: src/driver/DriverUtils.ts (hunk 4 above)
Comment (JoseCToscano) [reply src/driver/DriverUtils.ts:137]: That does sound like some edge case that could bring up some issue 🤔 . Haven't really worked with it. How does postgress handles the syntax for nested relations?

File: src/driver/DriverUtils.ts (hunk 3 above)
Comment (JoseCToscano) [reply src/driver/DriverUtils.ts:135]: That's some nice insight. I do think it should be defined somewhere in the repo, otherwise, where is it taking it from?. I'll see if I can find it, maybe we can work the solution through there 👀

Comment (felix-gohla) [reply src/driver/DriverUtils.ts:135]: I think there are many places in the code which just assumes that there are no dots in the name of tables.
Maybe worth another issue. There is already #3531. Maybe there somewhere hides a function that escapes names or something. However, not sure if this is out of scope for this PR.

Comment (JoseCToscano) [reply src/driver/DriverUtils.ts]: Just made an update to the PR. By using relationName instead of relationPath, we do not need to parse for any "." to get the relations. So we won't encounter issues with the table names. (At least not in this section, it seems the full support for them is still missing in the repo😅 )

File: src/find-options/FindOptionsUtils.ts [hunk 5]
```diff
@@ -391,7 +391,7 @@ export class FindOptionsUtils {
                 qb.connection.driver,
                 { joiner: "__" },
                 alias,
-                relation.propertyPath,
+                relation.propertyName,
```
Comment (JoseCToscano) [inline src/find-options/FindOptionsUtils.ts:394]: @felix-gohla 
This was the main issue, breaking nested relations. There was not really the need of  parsing "." to distinguish relations

File: src/driver/DriverUtils.ts (hunk 4 above)
Comment (JoseCToscano) [reply src/driver/DriverUtils.ts]: Just removed this section that previously added, it was not needed at all

File: src/find-options/FindOptionsUtils.ts (hunk 5 above)
Comment (felix-gohla) [reply src/find-options/FindOptionsUtils.ts:394]: This is great! 😊 Simple solutions are always the best!

**Review by felix-gohla — APPROVED** [review]
I also tested this version against our project's internal test suite and everything seems fine back again. Thank you very much for investigating, @JoseCToscano! 😊 

Maybe rebase onto the latest master and then @pleerock or one of the other maintainers can have a look at this.

**Comment by felix-gohla** [comment]
@pleerock @AlexMesser Is there something we can do to support you? Issues and MRs are somehow piling up... 🙃

**Comment by JoseCToscano** [comment]
Just synced master

**Comment by felix-gohla** [comment]
@JoseCToscano Did you per chance find a possibility to use typeorm directly from source (to include the patch without waiting for reaction of the maintainers and a release)?
We could use some kind of post-install script to build typeorm but this is not an ideal situation... :D

**Comment by JoseCToscano** [comment]
> 

I've been testing locally TypeORM by packaging a local version of TypeORM and then installing it on my Project's repo (just ``` npm install '../../../../typeom-fork/typeorm/build/package' ```
but I don't know if this is what you are looking for. Maybe publishing a forked version to your own npm organization/project and installing that directly?

**Review by hinogi — APPROVED** [review]
LGTM

**Comment by pleerock** [comment]
@JoseCToscano  thanks for the fix and sorry for late review. The summer was really hot 🌞 . Thanks @felix-gohla @hinogi  for the review help!
