### PR TITLE
fix: attach FOR NO KEY UPDATE lock to query if required

### LINKED ISSUE #7717: PostgreSQL - Repository find lock mode for_no_key_update is not being added to query
## Issue Description
When using lock mode for_no_key_update in find method like this:
`repository.find({ lock: { mode: 'for_no_key_update' } })`
Output query does not have lock.

The reason is missing  'for_no_key_update' check in FindOptionsUtils.ts https://github.com/typeorm/typeorm/blob/beea2e1e4429d13d7864ebc23aa6e58fa01647ea/src/find-options/FindOptionsUtils.ts#L184

### Expected Behavior

In case of pg driver, I expect adding ` FOR NO KEY UPDATE` to the end of `SELECT ...`, same as using lock method for QueryBuilder.

### Actual Behavior

Lock is not added because of skipping it on repository level and missing on query builder error.
So resulting query is simple select.

```

```

### Steps to Reproduce

1. Set lock mode for_no_key_update in find method of repository

```typescript
`repository.find({ lock: { mode: 'for_no_key_update' } })`
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14 | 
| Typescript version  | v4.1 | 
| TypeORM version     | v0.2.32 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by das-mensch**
### Description of change

FOR NO KEY UPDATE was introduced in typeorm 0.2.25 but the relevant query
part was never added due to missing check in FindOptionUtils as @ykovalenko-gentech
stated out. I've added a test to ensure this behaviour will not change in the future.

Fixes #7717

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change *N/A*
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/find-options/FindOptionsUtils.ts [hunk 1]
```diff
@@ -155,7 +155,14 @@ export class FindOptionsUtils {
         if (options.lock) {
             if (options.lock.mode === "optimistic") {
                 qb.setLock(options.lock.mode, options.lock.version);
-            } else if (options.lock.mode === "pessimistic_read" || options.lock.mode === "pessimistic_write" || options.lock.mode === "dirty_read" || options.lock.mode === "pessimistic_partial_write" || options.lock.mode === "pessimistic_write_or_fail") {
+            } else if (
+                options.lock.mode === "pessimistic_read" ||
```
Comment (YuriiKovalenko) [inline src/find-options/FindOptionsUtils.ts:159]: Is it better to store all possible locks in const array and call `array.includes()` instead of chaining equality checks.

Comment (das-mensch) [reply src/find-options/FindOptionsUtils.ts:159]: Absolutely. The locking code base seems to have grown a lot in the past and needs some refactoring. I would like to create a separate PR for cleaning up. This is more like a "hot fix"

**Comment by das-mensch** [comment]
Is there a way to re-trigger the circleci test for cockroachdb? It seems it may just hung up. Not quite familiar with cockroachdb...

**Comment by pleerock** [comment]
Thank you for contribution! 🎉
