### PR TITLE
fix: add mssql disableAsciiToUnicodeParamConversion option and tests

### LINKED ISSUE #10131: MssqlParameter of type varchar is being treated like nvarchar
### Issue description

MssqlParameter of type varchar is being treated like nvarchar 

### Expected Behavior

We are using TypeORM to connect to a MSSQL Server DB.  A number of our tables have `varchar` columns with indexes on them which we filter on in our WHERE clauses.  For example:

```
andWhere('"name" = :firstName', {
   firstName: new MssqlParameter('Bill', 'varchar', 100)
})
```

In previous versions of TypeORM (e.g. 0.2.33), this parameter was correctly treated like a `varchar` in the resulting queries that hit the database.  This led to performant queries that properly utilized our desired indexes.  

### Actual Behavior

However, in versions 0.3.x we are observing this parameter is now being treated as an `nvarchar` which is causing implicit conversion and our query performance to plummet.  

This seems to have been introduced by this PR: https://github.com/typeorm/typeorm/pull/7933 which appears to be intentionally disregarding the explicitly declared parameter types when they are `varchar` or `char`.  This seems like a very poor solution to the original problem and surely must be causing significant performance issues for anyone querying against `varchar` columns like this.  We've tried a number of other approaches and every way we declare this parameter it ends up being converted to an `nvarchar` before it hits the database.

### Steps to reproduce

I don't have a minimal example right now but this appears to be consistently reproducible when querying against a `varchar` column in a MSSQL Server DB using a `varchar` parameter in the `WHERE` clause.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.17.0  |
| Typescript version  | 4.7.4  |
| TypeORM version     | 0.3.16  |
| Database     | MSSQL Server  |

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [X] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by nadiamk**
This adds a new property `disableAsciiToUnicodeParamConversion` to `SqlServerConnectionOptions` to control whether the `MssqlParameter` types `char`, `varchar`, and `text` are converted to their unicode equivalents `nchar`, `nvarchar`, and `ntext`. This defaults to `false`, maintaining the current behavior.

Example:
```
andWhere('"name" = :firstName', {
   firstName: new MssqlParameter('Bill', 'varchar', 100)
})
```
- The current behavior: `firstName` is treated as an `nvarchar`
- This PR introduces configuring this behavior: setting `disableAsciiToUnicodeParamConversion` to `true` treats `firstName` as `varchar`. If `disableAsciiToUnicodeParamConversion` is set to `false` or omitted from the ORM configuration values, `firstName` remains `nvarchar`

See full description of the issue, including the motivation, in https://github.com/typeorm/typeorm/issues/10131

Fixes #10131

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] `npm run format` to apply prettier formatting
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mattnohelty-mastery** [comment]
This looks great to me and should solve the problem I reported in https://github.com/typeorm/typeorm/issues/10131.  I think it would be more correct default behavior for `disableAsciiToUnicodeParamConversion` to be `true` but in the spirit of maintaining backward compatibility, defaulting to `false` makes sense.

File: src/driver/sqlserver/SqlServerQueryRunner.ts [hunk 1]
```diff
@@ -4049,12 +4049,33 @@ export class SqlServerQueryRunner
...
             case "char":
+                if (
+                    this.driver.options.options
+                        ?.disableAsciiToUnicodeParamConversion
+                ) {
+                    return this.driver.mssql.Char(...parameter.params)
+                }
+                return this.driver.mssql.NChar(...parameter.params)
             case "nchar":
                 return this.driver.mssql.NChar(...parameter.params)
```
Comment (hinogi) [inline src/driver/sqlserver/SqlServerQueryRunner.ts:4060]:
```suggestion
            case "char":
                if (
                    this.driver.options.options
                        ?.disableAsciiToUnicodeParamConversion
                ) {
                    return this.driver.mssql.Char(...parameter.params)
                }
            case "nchar":
                return this.driver.mssql.NChar(...parameter.params)
```
No idea if duplication of fall through is worse :D

**Review by hinogi — APPROVED** [review]
LGTM

File: src/driver/sqlserver/SqlServerQueryRunner.ts (hunk 1 above)
Comment (nadiamk) [reply src/driver/sqlserver/SqlServerQueryRunner.ts:4060]: Thank you for the review! 

I'm happy to make the change, but question - the conditional in the "char" case is triggering "TS7029: Fallthrough case in switch" due to tsconfig.json's `"noFallthroughCasesInSwitch": true"`. Would you still like me to make the change, bypassing the error with a `// @ts-ignore`?

Comment (hinogi) [reply src/driver/sqlserver/SqlServerQueryRunner.ts:4060]: as I said, both is not nice, just keep your version.

**Comment by AlexMesser** [comment]
thank you for contribution!

**Comment by sudhirt4** [comment]
Would it be possible to have this enabled by default ? 

For anyone just coming into typeorm and using SQL server database, this context of this configuration is not visible. And for cases like when "varchar" column is used, runtime type conversion leads to a point of failure only known later when scaling.

**Comment by mguida22** [comment]
> Would it make sense to have this enabled by default ?

I think so. @sudhirt4 can you open a new issue to track changing the default? We can discuss the implications and how to release there.
