### PR TITLE
fix: prevent dropping materialized views on Postgres versions < 9.3

### LINKED ISSUE #7714: PostgreSQL - QueryFailedError: relation "pg_matviews" does not exist
## Issue Description
After updating from 0.2.32 to [0.2.33](https://github.com/typeorm/typeorm/compare/0.2.33...master)-[34](https://github.com/typeorm/typeorm/compare/0.2.34...master), the pg driver tries to select a non-existent relation "pg_matviews"

### Actual Behavior
```sh
query: START TRANSACTION
query: SELECT 'DROP VIEW IF EXISTS "' || schemaname || '"."' || viewname || '" CASCADE;' as "query" FROM "pg_views" WHERE "schemaname" IN (current_schema()) AND "viewname" NOT IN ('geography_columns', 'geometry_columns', 'raster_columns', 'raster_overviews')
query: SELECT 'DROP MATERIALIZED VIEW IF EXISTS "' || schemaname || '"."' || matviewname || '" CASCADE;' as "query" FROM "pg_matviews" WHERE "schemaname" IN (current_schema())
query failed: SELECT 'DROP MATERIALIZED VIEW IF EXISTS "' || schemaname || '"."' || matviewname || '" CASCADE;' as "query" FROM "pg_matviews" WHERE "schemaname" IN (current_schema())
error: error: relation "pg_matviews" does not exist
    at Parser.parseErrorMessage (/home/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 103,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '115',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '874',
  routine: 'parserOpenTable'
}
query: ROLLBACK
```

### Steps to Reproduce
1. Run `npm i typeorm@0.2.33`
2. Create docker-compose.yaml
```yaml
version: '3.5'
services:
  postgres:
    image: mdillon/postgis:9.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
```
3. Use this TypeORM options:
```json
{
  "name": "development",
  "type": "postgres",
  "host": "localhost",
  "port": 5432,
  "cache": true,
  "logging": "all",
  "database": "database",
  "username": "postgres",
  "password": "postgres",
  "dropSchema": true,
  "synchronize": true,
  "migrationsRun": true,
}
``` 

### My Environment
| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |     Solus OS 4.2     |
| Node.js version     | 14.17.0 |
| Typescript version  | 4.3.2 |
| TypeORM version     | 0.2.23^ |
| PostGIS | 9.2 |

### Relevant Database Driver(s)
- [x] `postgres`

### Are you willing to resolve this issue by submitting a Pull Request?
- [x] No, I don't have the time, although I believe I could do it if I had the time...

### PR DESCRIPTION
**Pull request by AlexMesser**
### Description of change

Materialized views introduced in Postgres 9.3. This PR adds version check before dropping materialized views to prevent errors on Postgres versions lower than 9.3

Fixes #7714

### Pull-Request Checklist

- [ ] Code is up-to-date with the `master` branch
- [ ] `npm run lint` passes with this change
- [ ] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by H6LS1S — APPROVED** [review]

**Review by imnotjames — APPROVED** [review]
We can probably cache the version but this works anyway.

**Comment by imnotjames** [comment]
However, I agree with the comment in the related issue:

> [Postgres 9.2](https://www.postgresql.org/support/versioning/) official support was ended in 2017. We can't keep backward compatibility for all existing database versions.

It'd be easier to update the documentation to just say we require Postgres >= 9.3

File: src/driver/postgres/PostgresQueryRunner.ts [hunk 1]
```diff
@@ -1917,6 +1922,14 @@ export class PostgresQueryRunner extends BaseQueryRunner implements QueryRunner
         return new Query(sql);
     }
 
+    /**
+     * Loads Postgres version.
+     */
+    protected async getVersion(): Promise<string> {
```
Comment (mitsos1os) [inline src/driver/postgres/PostgresQueryRunner.ts:1928]: Wouldn't it be better if `getVersion` moved to **PostgresDriver**, also cache the result as a property in the driver that could later be used directly in any subsequent scenarios? (ex: https://github.com/typeorm/typeorm/pull/7741)
