### PR TITLE
fix(mysql): support AnalyticDB returning version() column name in getVersion()

### LINKED ISSUE #11553: Bug: getVersion() fails with AnalyticDB MySQL due to non-standard field name version()
### Issue description

When using TypeORM with Alibaba Cloud AnalyticDB for MySQL (ADS), the `getVersion()` function in `MysqlQueryRunner` fails due to ADS returning the version information under the key `version()` instead of `version`.  This causes a TypeError when calling `.replace()` on undefined if `result[0].version` is not available.  Related driver: mysql / mysql2

### Expected Behavior

TypeORM should correctly parse the version string returned from ADS, even when the field name is `version()`, and not throw an error.

### Actual Behavior

TypeORM crashes with:

TypeError: Cannot read properties of undefined (reading 'replace')
    at MysqlQueryRunner.getVersion (...)

The query result from ADS is:

[ { 'version()': '5.6.16-log' } ]

In the current implementation, `result[0].version` is undefined, and `result[0]['version()']` should be used instead.

### Steps to reproduce

1. Use TypeORM with `type: 'mysql'`
2. Connect to Alibaba Cloud AnalyticDB for MySQL (ADS)
3. Let TypeORM call `getVersion()` internally
4. Observe TypeError when parsing the version string

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |    macos      |
| Node.js version     | 22.0.0 |
| Typescript version  | 5.1.3 |
| TypeORM version     | 0.3.25  |

### Additional Context

_No response_

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

### PR DESCRIPTION
**Pull request by Minglu-Huo**
### Description of change

When using Alibaba Cloud AnalyticDB for MySQL (ADS), running `SELECT VERSION() AS version` returns a column named `version()` instead of `version`, which causes TypeORM to throw a TypeError in `MysqlQueryRunner.getVersion()`.

This change updates `getVersion()` to support both `version` and `version()` column keys, making it compatible with ADS while keeping compatibility with standard MySQL and MariaDB.

Verified locally using ADS instance, and also tested on standard MySQL.

Related issue: https://github.com/typeorm/typeorm/issues/11553

---

### Pull-Request Checklist

-   [x] Code is up-to-date with the `master` branch
-   [x] This pull request links relevant issues as `Fixes #11553`
-   [ ] There are new or updated unit tests validating the change (N/A)
-   [ ] Documentation has been updated to reflect this change (N/A)

---

🎉 Thank you for reviewing this PR!

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved compatibility when retrieving MySQL version information, ensuring the version is correctly detected regardless of how the database returns the version string.

### CODE REVIEW

**Comment by rhydian0x** [comment]
Hi @alumni , could you please help review this PR when you have time? Thanks!

File: src/driver/mysql/MysqlQueryRunner.ts [hunk 1]
```diff
@@ -3371,16 +3371,25 @@ export class MysqlQueryRunner extends BaseQueryRunner implements QueryRunner {
     }
 
     async getVersion(): Promise<string> {
-        const result: [{ version: string }] = await this.query(
+        const result = await this.query(
             `SELECT VERSION() AS \`version\``,
```
Comment (alumni) [inline src/driver/mysql/MysqlQueryRunner.ts]: Let's simplify. As discussed in the issue, `SELECT version()` would work on all versions:

```suggestion
        const result: [{ "version()": string }] = await this.query(
            `SELECT version()`,
```

File: src/driver/mysql/MysqlQueryRunner.ts [hunk 2]
```diff
@@ -3371,16 +3371,25 @@ export class MysqlQueryRunner extends BaseQueryRunner implements QueryRunner {
...
-        const versionString = result[0].version
+
+        // support AnalyticDB for MySQL returning version() column name in getVersion
+        const row = result[0] as { version?: string; "version()"?: string };
+
+        const versionString = row.version ?? row["version()"];
+
+        if (!versionString) {
+            throw new TypeORMError("Unable to determine database version: neither 'version' nor 'version()' property found in query result");
+        }
```
Comment (alumni) [inline src/driver/mysql/MysqlQueryRunner.ts]: Now, this whole thing would become:

```suggestion
        const versionString = result[0]["version()"]
```

**Review by alumni — CHANGES_REQUESTED** [review]

**Comment by rhydian0x** [comment]
@alumni 
Thanks! Updated the code as suggested. Please take another look when you have time 🙏

**Comment by alumni** [comment]
@Minglu-Huo the format check will fail if I will start the workflow :) Could you fix the formatting? Thanks :)

`npm run format` if your editor is not set up to use prettier.

**Comment by rhydian0x** [comment]
@alumni 
✅ Done. I’ve run npm run format and pushed the changes.

File: src/driver/mysql/MysqlQueryRunner.ts [hunk 3]
```diff
@@ -3371,16 +3371,18 @@ export class MysqlQueryRunner extends BaseQueryRunner implements QueryRunner {
     }
 
     async getVersion(): Promise<string> {
-        const result: [{ version: string }] = await this.query(
-            `SELECT VERSION() AS \`version\``,
+        const result: [{ "version()": string }] = await this.query(
+            `SELECT VERSION()`,
```
Comment (alumni) [inline src/driver/mysql/MysqlQueryRunner.ts]:
```suggestion
            `SELECT version()`,
```

otherwise, the line below will throw an exception.

**Comment by rhydian0x** [comment]
Thanks @alumni for the feedback! I've updated the query to use lowercase `version()` as suggested to avoid the exception.

**Review by alumni — APPROVED** [review]

**Comment by alumni** [comment]
Thanks for the fix 😀

**Review by gioboa — APPROVED** [review]
Thanks for your help @Minglu-Huo 👍

**Comment by rhydian0x** [comment]
@alumni 
Hi, thanks for merging the PR! I was wondering when this change will be published in a release?
